project_id = "yzlbtfhjohjhnqjbtmjn"

[functions.delete-auth-user]
verify_jwt = true

[functions.prime-metabase-insights]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.send-ticket-email]
verify_jwt = true

[functions.zendesk-tickets]
verify_jwt = true

[functions.zendesk-integration]
verify_jwt = true

[functions.zendesk-diagnostics]
verify_jwt = true

[functions.metabase-embed-token]
verify_jwt = true

[functions.market-analysis]
verify_jwt = true